language: python
python:
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-test.txt
  - pip install codecov
install:
  - pip install ".[test]" . # install package + test dependencies
script: pytest # run tests
after_success:
  - codecov # submit coverage